export default [
  { code: "BARCZWHXXXX", name: "FIRST CAPITAL BANK" },
  { code: "ZDBLZWHAXXX", name: "INFRASTRUCTURE DEV BANK ZIM" },
  { code: "CABSZWHAXXX", name: "CABS" },
  { code: "EMPWZWHXXXX", name: "EMPOWERBANK" },
  { code: "MBOZZWHAXXX", name: "METBANK" },
  { code: "ZWMFZWHAXXX", name: "ZWMBANK" },
  { code: "SMFBZWHAXXX", name: "SUCCESS" },
  { code: "SCBLZWHXXXX", name: "FBC CROWN" },
  { code: "NDORZWHXXXX", name: "INNBUCKS" },
  { code: "ZBCOZWHXXXX", name: "ZB BANK" },
  { code: "STBLZWHXXXX", name: "STEWARD" },
  { code: "GBSPZWHAXXX", name: "GETBUCKS" },
  { code: "NABYZWHAXXX", name: "NBS" },
  { code: "AFCNZWHAXXX", name: "AFRICAN CENTURY LIMITED" },
  { code: "PWSBZWHXXXX", name: "POSB" },
  { code: "MBCAZWHXXXX", name: "NEDBANK LTD" },
  { code: "ECOCZWHXXXX", name: "ECOBANK" },
  { code: "COBZZWHAXXX", name: "CBZ" },
  { code: "NMBLZWHXXXX", name: "NMBZ" },
  { code: "FBCPZWHAXXX", name: "FBC BANK LTD" },
  { code: "FMBZZWHXXXX", name: "BANCABC" },
  { code: "LMLDZWHAXXX", name: "LION FINANCE" },
  { code: "SBICZWHXXXX", name: "STANBIC" }
];
